### ISSUE TITLE
Seperate app for iPadOS

### ISSUE THREAD

**Issue by Veethahavya** [anyproto/anytype-swift#402]
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing requests and didn't find any that were similar
- [X] I have considered creating a pull request instead and want to proceed

### Clear and concise description of the problem

Hello Team Any,

Thank you for building on such an interesting project!
I am a new adapter of the anytype application and I wish to use it for my workflow (moving from Obsidian).

So, the issue I have is with the iOS app, or actually the lask of an iPadOS app.
The current iOS app uses only a small portion of the iPad's scree and that is not very ideal and neither is it nearly a good an experience as the desktop clients provide.

### Suggested solution

Therefore, I request the tem to consider making a seperate app for iPads.

### Alternative

 or maybe dynamically using the canvas screen available to the device?

**Comment by kmordan** [comment]
Hey, @Veethahavya!
In the upcoming release, we will ship a small improvement by increasing the editor width to make full use of the screen size on iPads (Please, check attached video in PR #391).

We're definitely aware of the need for full support on iPadOS, but I can't provide a specific timeline right now because our priorities and team size limit us. 
Nevertheless, we're gradually moving in that direction by taking small steps ✌️

**Comment by mgolovko** [comment]
@milesmcclane, Hello! Anytype app support iPhone and iPad. We continue to evolve one app for all platforms. We plan to improve the iPad experience, including better layout, multi-window and apple pencil. 🙂

**Comment by drmop** [comment]
Hello, i have the same request for iPadOS.
I love the sidebar on Mac/Win/Linux which makes it easy to switch on tabs, but the problem is the sidebar is missing on iPadOS.
Every time if I want to return, it takes a lot of efforts just to click on a small button or swipe a large distance, which makes a very bad UX. Can't there be a sidebar for iPadOS just like the desktop version?

**Comment by ignatovv** [comment]
Hello everyone. We use [community forum](https://community.anytype.io/) as a single source of truth for product feature requests. We are using Github only for engineering related issues, where no product team members should be involved. Feel free to create feature request there if it's still an actual thing.
